language: node_js
node_js:
  - "10"
addons:
  chrome: stable
install:
  - npm install
jobs:
  include:
    - stage: test
      name: "Lint"
      script: npm run lint
    - script: npm run test-ci
      name: "Test"
